name: AMD Offline Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - triton-mlir

jobs:
  Integration-Tests:
    runs-on: "ubuntu-latest"

    container:
      image: rocm/rocm-terminal
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clear cache
        run: |
          rm -rf ~/.triton

      - name: Update PATH
        run: |
          echo "PATH=${HOME}/.local/bin:${PATH}" >> "${GITHUB_ENV}"

      # - name: Check pre-commit
      #   if: ${{ matrix.runner != 'macos-10.15' }}
      #   run: |
      #     apt remove -y cmake
      #     apt update
      #     apt install -y git
      #     # python3 -m pip install --upgrade pre-commit
      #     # python3 -m pre_commit run --all-files

      - name: Prerequisite
        run: |
          # remove system cmake to use python cmake instead
          apt remove -y cmake
          pip3 install cmake
          apt update
          apt install -y libpython3.8-dev

      - name: Install Triton
        run: |
          cd python
          # python3 -m pip install --upgrade pip
          # python3 -m pip install cmake==3.24
          python3 -m pip install torch==1.13.1 --index-url https://download.pytorch.org/whl/rocm5.2
          DEBUG=TRUE TRITON_USE_ROCM=TRUE TRITON_USE_ASSERT_ENABLED_LLVM=TRUE python3 -m pip install --no-build-isolation -vvv -e '.[tests]'

      - name: Run lit tests
        run: |
          python3 -m pip install lit
          cd python
          LIT_TEST_DIR="build/$(ls build | grep -i cmake)/test"
          if [ ! -d "${LIT_TEST_DIR}" ]; then
            echo "Could not find '${LIT_TEST_DIR}'" ; exit -1
          fi
          lit -v "${LIT_TEST_DIR}"

      - name: Run CXX unittests
        run: |
          cd python
          cd "build/$(ls build | grep -i cmake)"
          ctest
