name: CI

on:
  push:
    branches:
      - shared/gfx1250*
  pull_request:
    branches:
      - shared/gfx1250*
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  gfx1250-gluon:
    name: Gluon
    runs-on: ['self-hosted', 'ffm']
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test Gluon
        run: |
          set -xeo pipefail
          RENDER_GID=$(getent group render | cut -d: -f3)
          echo "Render group ID: ${RENDER_GID}"
          docker run --pull=never --rm \
            --device=/dev/kfd --device=/dev/dri --group-add video --group-add $RENDER_GID \
            --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
            --shm-size=16G --ulimit memlock=-1 --ulimit stack=67108864 \
            -v /data/ci/actions-runner/_work/triton/triton:/code \
            -v /data/ci/llvm/a992f294-release:/llvm \
            -v /data/ci/ffm/rocm-ffmlite-mi450-1318-ce0033dd-rel-20251222:/ffm-base \
            -v /data/ci/ffm/ffmlite-main-503fe115-20260109:/ffm-update \
            -v /data/ci/triton-cache:/home/mirror/.triton \
            -v /data/ci/ccache:/home/mirror/.ccache \
            -w /code \
            --entrypoint bash \
            ci/gfx1250-env -lc "/code/.github/workflows/gluon.sh"

  gfx1250-triton:
    name: Triton
    runs-on: ['self-hosted', 'ffm', 'pytorch']
    timeout-minutes: 50

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test Triton
        run: |
          set -xeo pipefail
          RENDER_GID=$(getent group render | cut -d: -f3)
          echo "Render group ID: ${RENDER_GID}"
          docker run --pull=never --rm \
            --device=/dev/kfd --device=/dev/dri --group-add video --group-add $RENDER_GID \
            --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
            --shm-size=16G --ulimit memlock=-1 --ulimit stack=67108864 \
            -v /data/ci/actions-runner/_work/triton/triton:/code \
            -v /data/ci/llvm/a992f294-release:/llvm \
            -v /data/ci/ffm/rocm-ffmlite-mi450-1318-ce0033dd-rel-20251222:/ffm-base \
            -v /data/ci/ffm/ffmlite-main-503fe115-20260109:/ffm-update \
            -v /data/ci/triton-cache:/home/mirror/.triton \
            -v /data/ci/ccache:/home/mirror/.ccache \
            -w /code \
            --entrypoint bash \
            ci/gfx1250-pytorch-env -lc "/code/.github/workflows/triton.sh"
